runner:
  golint:
    cmd: golint $(go list ./... | grep -v /vendor/)
    format: golint
    level: warning
  govet:
    cmd: go build -o /tmp/linter linter.go && go vet -vettool=/tmp/linter ./... && rm /tmp/linter
    format: golint
